begin;

create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  campaign_id bigint not null
    references public.campaigns(id) on delete cascade,
  campaign_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (auth_user_id, campaign_id)
);

create index if not exists user_favorites_owner_created_idx
  on public.user_favorites (auth_user_id, created_at desc);

create table if not exists public.user_campaign_records (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  campaign_id bigint null
    references public.campaigns(id) on delete set null,
  source_type text not null
    check (source_type in ('linked', 'manual')),
  status text not null default 'saved'
    check (
      status in (
        'saved',
        'applied',
        'selected',
        'visited',
        'review_pending',
        'completed',
        'cancelled'
      )
    ),
  title text not null,
  platform text null,
  link text null,
  reward text null,
  region text null,
  deadline_at timestamptz null,
  note text null,
  campaign_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists user_campaign_records_owner_campaign_uidx
  on public.user_campaign_records (auth_user_id, campaign_id)
  where campaign_id is not null;

create index if not exists user_campaign_records_owner_deadline_idx
  on public.user_campaign_records (
    auth_user_id,
    deadline_at asc nulls last,
    created_at desc
  );

commit;
