begin;

create table if not exists public.user_campaign_settlements (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  record_id bigint not null
    references public.user_campaign_records(id) on delete cascade,
  expected_cash_amount integer null
    check (expected_cash_amount is null or expected_cash_amount >= 0),
  expected_provided_value_amount integer null
    check (expected_provided_value_amount is null or expected_provided_value_amount >= 0),
  expected_points_amount integer null
    check (expected_points_amount is null or expected_points_amount >= 0),
  expected_reimbursement_amount integer null
    check (expected_reimbursement_amount is null or expected_reimbursement_amount >= 0),
  actual_cash_received_amount integer null
    check (actual_cash_received_amount is null or actual_cash_received_amount >= 0),
  actual_reimbursement_received_amount integer null
    check (
      actual_reimbursement_received_amount is null
      or actual_reimbursement_received_amount >= 0
    ),
  cash_received_at timestamptz null,
  reimbursement_received_at timestamptz null,
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (auth_user_id, record_id)
);

create index if not exists user_campaign_settlements_owner_updated_idx
  on public.user_campaign_settlements (auth_user_id, updated_at desc);

create index if not exists user_campaign_settlements_record_idx
  on public.user_campaign_settlements (auth_user_id, record_id);

commit;
