begin;

create table if not exists public.user_campaign_tasks (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  record_id bigint not null
    references public.user_campaign_records(id) on delete cascade,
  task_type text not null
    check (task_type in ('visit', 'content', 'submit', 'other')),
  title text not null,
  due_at timestamptz not null,
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_campaign_tasks_owner_due_idx
  on public.user_campaign_tasks (
    auth_user_id,
    completed_at,
    due_at asc,
    created_at desc
  );

create index if not exists user_campaign_tasks_record_idx
  on public.user_campaign_tasks (auth_user_id, record_id);

commit;
