-- Track candidate and active campaign source platforms separately from campaign data.

create table if not exists public.platform_sources (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  base_url text not null,
  status text not null default 'candidate'
    check (status in ('candidate', 'active', 'paused', 'blocked')),
  priority smallint not null default 100,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.platform_sources enable row level security;

revoke all on public.platform_sources from anon, authenticated;
grant select, insert, update, delete on public.platform_sources to service_role;

insert into public.platform_sources (slug, name, base_url, status, priority, notes)
values
  ('4blog', '포블로그', 'https://4blog.net/', 'candidate', 10, '방문/배송 및 다양한 SNS 채널. 우선 구조 분석 대상.'),
  ('dinnerqueen', '디너의여왕', 'https://dinnerqueen.net/', 'candidate', 20, '지역형 체험단 규모가 크고 신청/모집/마감 데이터가 잘 노출됨.'),
  ('mible', '미블', 'https://www.mrblog.net/', 'candidate', 30, '지역/배송 캠페인과 제공내역 데이터 구조 확인 대상.'),
  ('reviewplace', '리뷰플레이스', 'https://www.reviewplace.co.kr/', 'candidate', 40, '제품/지역/기자단/구매평 등 유형이 다양함.'),
  ('reviewus', '리뷰어스', 'https://kr.reviewus.co.kr/', 'candidate', 50, '블로그/인스타/배송형 캠페인 후보.')
on conflict (slug) do update
set
  name = excluded.name,
  base_url = excluded.base_url,
  status = excluded.status,
  priority = excluded.priority,
  notes = excluded.notes,
  updated_at = now();
